services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - data-stack-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres-gold
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - data-stack-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.156.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./infra/otel/collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "${OTEL_COLLECTOR_OTLP_HTTP_PORT}:4318"
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - data-stack-network

volumes:
  minio_data:
  postgres_data:

networks:
  data-stack-network:
    external: true